-- #1
SELECT * FROM northwind.customers;
-- #2
SELECT DISTINCT Country_region FROM Customers;
-- #3
SELECT * FROM northwind.customers
WHERE last_name like 'B%';
-- #4
SELECT * FROM northwind.customers
LIMIT 100;
-- #5
SELECT * FROM northwind.customers
WHERE ZIP_POSTAL_CODE='1010'
OR ZIP_POSTAL_CODE = '3012'
OR ZIP_POSTAL_CODE = '12209'
OR ZIP_POSTAL_CODE = '05023';
-- #5.1
SELECT * FROM northwind.customers
WHERE ZIP_POSTAL_CODE IN ('1010','3012','12209','05023');
--#6
SELECT * FROM northwind.orders
WHERE SHIP_COUNTRY_REGION IS NOT NULL;
--#6.1
SELECT * FROM northwind.orders
WHERE SHIP_COUNTRY_REGION NOT LIKE 'NULL';
--#7
SELECT * FROM northwind.customers
ORDER BY COUNTRY_REGION, CITY;
--#8
INSERT INTO CUSTOMERS (ID, LAST_NAME, FIRST_NAME, JOB_TITLE)
VALUES (30, 'JOHNSON', 'JOHN', 'STUDENT');
--#9
UPDATE ORDERS
SET SHIP_ZIP_POSTAL_CODE='97201'
WHERE SHIP_CITY = 'PORTLAND';
--#10
DELETE FROM ORDER_DETAILS
WHERE QUANTITY = '1'; 
--#11
SELECT AVG(QUANTITY),MIN(QUANTITY), MAX(QUANTITY) FROM ORDER_DETAILS;
--#12
SELECT AVG(QUANTITY),MIN(QUANTITY), MAX(QUANTITY) FROM ORDER_DETAILS
GROUP BY ORDER_ID;
--#13
SELECT CUSTOMER_ID
FROM ORDERS
WHERE ID='65';
--#14
SELECT *
FROM ORDERS
INNER JOIN CUSTOMERS

SELECT CUSTOMERS.LAST_NAME, CUSTOMERS.FIRST_NAME, ORDERS.SHIP_NAME
FROM ORDERS
LEFT JOIN CUSTOMERS
ON ORDERS.CUSTOMER_ID=CUSTOMERS.ID;

SELECT CUSTOMERS.LAST_NAME, CUSTOMERS.FIRST_NAME, ORDERS.SHIP_NAME
FROM ORDERS
RIGHT JOIN CUSTOMERS
ON ORDERS.CUSTOMER_ID=CUSTOMERS.ID;
--#15
SELECT first_name from northwind.employees
WHERE notes is null; 
--#16
SELECT ship_city from northwind.orders
WHERE ship_name like 'Francisco%';